jira:
  # https://confluence.atlassian.com/cloud/api-tokens-938839638.html
  url: ${JIRA_URL}
  username: ${JIRA_USERNAME}
  token: ${JIRA_TOKEN}
  project: ${JIRA_PROJECT}

spring:
  main:
    banner-mode: off
